import { useState } from "react";
import { useTheme } from "../../context/ThemeContext";
import { FileText, Download, Loader2, X } from "lucide-react";

/*
  Client-side PDF generation using jsPDF + AutoTable.
  Loaded dynamically from CDN on first use — no npm dependency.
*/

let jsPDFLoaded = null;
function loadLibs() {
  if (jsPDFLoaded) return jsPDFLoaded;
  jsPDFLoaded = new Promise(async (resolve, reject) => {
    try {
      // jsPDF core
      if (!window.jspdf) {
        await new Promise((res, rej) => {
          const s = document.createElement("script");
          s.src =
            "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js";
          s.onload = res;
          s.onerror = rej;
          document.head.appendChild(s);
        });
      }
      // AutoTable plugin
      if (!window.jspdf?.jsPDF?.API?.autoTable) {
        await new Promise((res, rej) => {
          const s = document.createElement("script");
          s.src =
            "https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.4/jspdf.plugin.autotable.min.js";
          s.onload = res;
          s.onerror = rej;
          document.head.appendChild(s);
        });
      }
      resolve(window.jspdf);
    } catch (e) {
      reject(e);
    }
  });
  return jsPDFLoaded;
}

const C = {
  primary: [67, 56, 240],
  dark: [26, 23, 20],
  gray: [120, 120, 120],
  lightGray: [200, 200, 200],
  bg: [245, 243, 240],
  white: [255, 255, 255],
  red: [192, 57, 43],
  amber: [180, 83, 9],
  green: [26, 135, 84],
};

function scoreColor(s) {
  return s >= 80 ? C.green : s >= 50 ? C.amber : C.red;
}
function fmtDate(d) {
  return new Date(d).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

async function buildPDF({ site, scan, issues, org, whiteLabel, companyName }) {
  const { jsPDF } = await loadLibs();
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const m = 18;
  const cw = W - m * 2;
  let y = 0;

  const pages = scan?.summary_json?.pages || [];
  const open = issues.filter((i) => i.status === "open");
  const counts = { critical: 0, serious: 0, moderate: 0, minor: 0 };
  open.forEach((i) => {
    counts[i.impact] = (counts[i.impact] || 0) + 1;
  });
  const score = Math.round(scan?.score || 0);

  function footer(n) {
    doc.setFontSize(7);
    doc.setTextColor(...C.gray);
    doc.text(
      `Generated by ${whiteLabel ? companyName : "xsbl"} — ${fmtDate(
        new Date()
      )}`,
      m,
      H - 10
    );
    doc.text(`Page ${n}`, W - m, H - 10, { align: "right" });
  }

  function needPage(h) {
    if (y + h > H - 20) {
      footer(doc.getNumberOfPages());
      doc.addPage();
      y = m;
    }
  }

  function heading(text) {
    needPage(16);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...C.dark);
    doc.text(text, m, y);
    y += 2;
    doc.setDrawColor(...C.primary);
    doc.setLineWidth(0.6);
    doc.line(m, y, m + 30, y);
    y += 6;
  }

  // ── COVER PAGE ──
  doc.setFillColor(...C.primary);
  doc.rect(0, 0, W, 4, "F");
  y = 35;

  // Brand
  doc.setFontSize(whiteLabel ? 10 : 14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...(whiteLabel ? C.primary : C.dark));
  doc.text(whiteLabel ? companyName.toUpperCase() : "xsbl.", m, y);
  y += 10;

  // Title
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...C.dark);
  doc.text("Accessibility", m, y);
  y += 12;
  doc.text("Compliance Report", m, y);
  y += 16;

  doc.setDrawColor(...C.lightGray);
  doc.setLineWidth(0.3);
  doc.line(m, y, m + 80, y);
  y += 8;

  // Meta
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.gray);
  const meta = [
    `Domain: ${site.domain}`,
    `Scan date: ${fmtDate(scan?.completed_at || new Date())}`,
    `Standard: WCAG 2.2 Level AA + AAA`,
    `Pages scanned: ${scan?.pages_scanned || 1}`,
  ];
  if (org?.name) meta.push(`Organization: ${org.name}`);
  meta.forEach((line) => {
    doc.text(line, m, y);
    y += 5;
  });

  // Score box
  y += 10;
  doc.setFillColor(...C.bg);
  doc.roundedRect(m, y, 60, 50, 4, 4, "F");
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...scoreColor(score));
  doc.text(String(score), m + 30, y + 28, { align: "center" });
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.gray);
  doc.text("ACCESSIBILITY SCORE", m + 30, y + 38, { align: "center" });

  // Stats beside score
  const sx = m + 72;
  const labels = ["Total issues", "Critical", "Serious", "Moderate", "Minor"];
  const vals = [
    open.length,
    counts.critical,
    counts.serious,
    counts.moderate,
    counts.minor,
  ];
  const cols = [C.dark, C.red, C.red, C.amber, C.gray];
  labels.forEach((l, i) => {
    const ly = y + 4 + i * 9;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...C.gray);
    doc.text(l, sx, ly);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...cols[i]);
    doc.text(String(vals[i]), sx + 50, ly, { align: "right" });
  });
  y += 58;

  // Verdict banner
  const verdict =
    score >= 80
      ? "Substantially Compliant"
      : score >= 50
      ? "Partially Compliant"
      : "Non-Compliant";
  doc.setFillColor(...scoreColor(score));
  doc.roundedRect(m, y, cw, 12, 3, 3, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...C.white);
  doc.text(`VERDICT: ${verdict}`, W / 2, y + 8, { align: "center" });
  y += 18;
  footer(1);

  // ── EXECUTIVE SUMMARY ──
  doc.addPage();
  y = m;
  heading("Executive Summary");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.dark);
  const summary = `This report presents the results of an automated WCAG 2.2 accessibility scan of ${
    site.domain
  }, conducted on ${fmtDate(
    scan?.completed_at || new Date()
  )}. The scan analyzed ${
    scan?.pages_scanned || 1
  } page(s) using axe-core against WCAG 2.2 Level AA and AAA success criteria.\n\nThe site received an overall accessibility score of ${score}/100, with ${
    open.length
  } open issues identified: ${counts.critical} critical, ${
    counts.serious
  } serious, ${counts.moderate} moderate, and ${counts.minor} minor.${
    counts.critical > 0
      ? "\n\nCritical issues should be addressed immediately as they represent complete barriers to access for users with disabilities."
      : ""
  }`;
  const sl = doc.splitTextToSize(summary, cw);
  doc.text(sl, m, y);
  y += sl.length * 4 + 8;

  // Page breakdown table
  if (pages.length > 1) {
    heading("Per-Page Results");
    doc.autoTable({
      startY: y,
      head: [["Page", "Score", "Issues", "Status"]],
      body: pages.map((p) => {
        let path;
        try {
          path = new URL(p.url).pathname;
        } catch {
          path = p.url;
        }
        return [
          path,
          p.score != null ? String(Math.round(p.score)) : "Failed",
          String(p.issues_count || 0),
          p.score >= 80 ? "Passing" : p.score >= 50 ? "Needs work" : "Failing",
        ];
      }),
      margin: { left: m, right: m },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        lineColor: C.lightGray,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: C.primary,
        textColor: C.white,
        fontStyle: "bold",
      },
      alternateRowStyles: { fillColor: C.bg },
      columnStyles: {
        0: { cellWidth: 70 },
        1: { cellWidth: 20, halign: "center" },
        2: { cellWidth: 20, halign: "center" },
        3: { cellWidth: 25, halign: "center" },
      },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 3) {
          const v = data.cell.raw;
          data.cell.styles.textColor =
            v === "Failing" ? C.red : v === "Needs work" ? C.amber : C.green;
        }
      },
    });
    y = doc.lastAutoTable.finalY + 8;
  }
  footer(doc.getNumberOfPages());

  // ── ISSUE DETAILS ──
  doc.addPage();
  y = m;
  heading("Issue Details");

  const groups = [
    {
      label: "Critical",
      items: open.filter((i) => i.impact === "critical"),
      color: C.red,
    },
    {
      label: "Serious",
      items: open.filter((i) => i.impact === "serious"),
      color: C.red,
    },
    {
      label: "Moderate",
      items: open.filter((i) => i.impact === "moderate"),
      color: C.amber,
    },
    {
      label: "Minor",
      items: open.filter((i) => i.impact === "minor"),
      color: C.gray,
    },
  ].filter((g) => g.items.length > 0);

  for (const group of groups) {
    needPage(14);
    doc.setFillColor(...group.color);
    doc.roundedRect(m, y, cw, 8, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...C.white);
    doc.text(
      `${group.label.toUpperCase()} (${group.items.length})`,
      m + 4,
      y + 5.5
    );
    y += 12;

    // Deduplicate by rule + page
    const seen = new Set();
    const deduped = [];
    for (const iss of group.items) {
      const key = `${iss.rule_id}|${iss.page_url}`;
      if (!seen.has(key)) {
        seen.add(key);
        deduped.push({
          ...iss,
          count: group.items.filter(
            (x) => x.rule_id === iss.rule_id && x.page_url === iss.page_url
          ).length,
        });
      }
    }

    for (const iss of deduped) {
      needPage(28);

      doc.setFontSize(8.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...C.primary);
      doc.text(iss.rule_id, m, y);
      if (iss.count > 1) {
        doc.setFontSize(7);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...C.gray);
        doc.text(
          ` (${iss.count} instances)`,
          m + doc.getTextWidth(iss.rule_id) + 1,
          y
        );
      }
      y += 4;

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...C.dark);
      const dl = doc.splitTextToSize(iss.description || "", cw);
      doc.text(dl, m, y);
      y += dl.length * 3.5;

      if (iss.wcag_tags?.length) {
        y += 1;
        doc.setFontSize(7);
        doc.setTextColor(...C.primary);
        doc.text(`WCAG: ${iss.wcag_tags.join(", ")}`, m, y);
        y += 3.5;
      }
      if (iss.page_url) {
        doc.setFontSize(7);
        doc.setTextColor(...C.gray);
        try {
          doc.text(`Page: ${new URL(iss.page_url).pathname}`, m, y);
        } catch {
          doc.text(`Page: ${iss.page_url}`, m, y);
        }
        y += 3.5;
      }
      if (iss.element_selector) {
        doc.setFontSize(7);
        doc.setTextColor(...C.gray);
        doc.text(`Selector: ${iss.element_selector.slice(0, 100)}`, m, y);
        y += 3.5;
      }
      if (iss.fix_suggestion) {
        const fl = doc.splitTextToSize(`Fix: ${iss.fix_suggestion}`, cw - 8);
        const fh = fl.length * 3.5 + 4;
        needPage(fh + 2);
        doc.setFillColor(...C.bg);
        doc.roundedRect(m, y - 1, cw, fh, 2, 2, "F");
        doc.setFontSize(7);
        doc.setTextColor(...C.dark);
        doc.text(fl, m + 4, y + 2.5);
        y += fh + 2;
      }
      y += 4;
      doc.setDrawColor(...C.lightGray);
      doc.setLineWidth(0.15);
      doc.line(m, y - 2, m + cw, y - 2);
    }
  }

  // ── METHODOLOGY ──
  needPage(50);
  heading("Methodology");
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.dark);
  const meth = `This scan was performed using axe-core 4.10.2, an open-source accessibility testing engine maintained by Deque Systems. Pages were loaded in a real Chromium browser and tested against WCAG 2.2 Level AA and AAA success criteria.\n\nThe accessibility score is calculated based on passing rules versus violations, weighted by severity (critical 4x, serious 3x, moderate 2x, minor 1x).\n\nAutomated testing identifies approximately 30-40% of WCAG issues. A comprehensive accessibility audit should include manual testing with assistive technologies and user testing with people with disabilities.`;
  const ml = doc.splitTextToSize(meth, cw);
  doc.text(ml, m, y);
  y += ml.length * 3.5 + 4;

  // Add footers to all pages
  const total = doc.getNumberOfPages();
  for (let i = 2; i <= total; i++) {
    doc.setPage(i);
    footer(i);
  }

  const fname = `${
    whiteLabel && companyName
      ? companyName.replace(/\s+/g, "-").toLowerCase()
      : "xsbl"
  }-a11y-report-${site.domain.replace(/\./g, "-")}-${new Date()
    .toISOString()
    .slice(0, 10)}.pdf`;
  doc.save(fname);
  return fname;
}

// ── UI Component ──
export default function ReportGenerator({ site, scan, issues, org }) {
  const { t } = useTheme();
  const [showModal, setShowModal] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [whiteLabel, setWhiteLabel] = useState(false);
  const [companyName, setCompanyName] = useState(org?.name || "");
  const [done, setDone] = useState(false);

  const canGenerate = scan && scan.status === "complete";
  const isPro = ["pro", "agency"].includes(org?.plan);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      await buildPDF({
        site,
        scan,
        issues,
        org,
        whiteLabel: whiteLabel && isPro,
        companyName,
      });
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } catch (err) {
      console.error("PDF generation failed:", err);
    }
    setGenerating(false);
  };

  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        disabled={!canGenerate}
        style={{
          padding: "0.5rem 1rem",
          borderRadius: 8,
          border: `1.5px solid ${t.ink20}`,
          background: "none",
          color: t.ink,
          fontFamily: "var(--body)",
          fontSize: "0.82rem",
          fontWeight: 500,
          cursor: canGenerate ? "pointer" : "not-allowed",
          opacity: canGenerate ? 1 : 0.5,
          display: "flex",
          alignItems: "center",
          gap: "0.4rem",
        }}
      >
        <FileText size={14} strokeWidth={1.8} /> PDF Report
      </button>

      {showModal && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 200,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            background: "rgba(0,0,0,0.5)",
            backdropFilter: "blur(5px)",
            padding: "1rem",
          }}
          onClick={(e) => e.target === e.currentTarget && setShowModal(false)}
        >
          <div
            style={{
              background: t.cardBg,
              borderRadius: 14,
              width: "100%",
              maxWidth: 400,
              border: `1px solid ${t.ink08}`,
              boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
              padding: "1.5rem",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginBottom: "1rem",
              }}
            >
              <div
                style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}
              >
                <FileText size={18} color={t.accent} strokeWidth={1.8} />
                <h3
                  style={{
                    fontFamily: "var(--serif)",
                    fontSize: "1.1rem",
                    fontWeight: 700,
                    color: t.ink,
                    margin: 0,
                  }}
                >
                  PDF Report
                </h3>
              </div>
              <button
                onClick={() => setShowModal(false)}
                style={{
                  background: t.ink04,
                  border: "none",
                  borderRadius: 8,
                  padding: "0.3rem",
                  cursor: "pointer",
                  color: t.ink50,
                  display: "flex",
                }}
              >
                <X size={16} />
              </button>
            </div>

            <p
              style={{
                fontSize: "0.84rem",
                color: t.ink50,
                lineHeight: 1.6,
                marginBottom: "1rem",
              }}
            >
              Generate a professional compliance report with your latest scan
              results, per-page breakdown, and issue details.
            </p>

            {/* Report contents preview */}
            <div
              style={{
                padding: "0.8rem",
                borderRadius: 8,
                background: t.ink04,
                marginBottom: "1rem",
                fontSize: "0.76rem",
                color: t.ink50,
                lineHeight: 1.7,
              }}
            >
              <strong style={{ color: t.ink }}>Report includes:</strong>
              <br />
              Cover page with score and verdict
              <br />
              Executive summary
              <br />
              {(scan?.summary_json?.pages?.length || 0) > 1
                ? "Per-page score breakdown\n"
                : ""}
              All {issues.filter((i) => i.status === "open").length} open issues
              grouped by severity
              <br />
              WCAG criteria and fix suggestions
              <br />
              Methodology and disclaimer
            </div>

            {/* White-label option */}
            {isPro && (
              <div style={{ marginBottom: "1rem" }}>
                <label
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "0.5rem",
                    cursor: "pointer",
                    fontSize: "0.84rem",
                    color: t.ink,
                    marginBottom: "0.4rem",
                  }}
                >
                  <div
                    onClick={() => setWhiteLabel(!whiteLabel)}
                    style={{
                      width: 36,
                      height: 20,
                      borderRadius: 10,
                      padding: 2,
                      cursor: "pointer",
                      background: whiteLabel ? t.accent : t.ink20,
                      transition: "background 0.2s",
                      display: "flex",
                      alignItems: "center",
                    }}
                  >
                    <div
                      style={{
                        width: 16,
                        height: 16,
                        borderRadius: "50%",
                        background: "white",
                        transform: whiteLabel
                          ? "translateX(16px)"
                          : "translateX(0)",
                        transition: "transform 0.2s",
                        boxShadow: "0 1px 3px rgba(0,0,0,0.15)",
                      }}
                    />
                  </div>
                  White-label report
                </label>
                {whiteLabel && (
                  <input
                    value={companyName}
                    onChange={(e) => setCompanyName(e.target.value)}
                    placeholder="Your Company Name"
                    autoFocus
                    style={{
                      width: "100%",
                      padding: "0.5rem 0.7rem",
                      borderRadius: 6,
                      border: `1.5px solid ${t.ink20}`,
                      background: t.paper,
                      color: t.ink,
                      fontFamily: "var(--body)",
                      fontSize: "0.84rem",
                      outline: "none",
                      boxSizing: "border-box",
                    }}
                    onFocus={(e) => (e.target.style.borderColor = t.accent)}
                    onBlur={(e) => (e.target.style.borderColor = t.ink20)}
                  />
                )}
              </div>
            )}
            {!isPro && (
              <p
                style={{
                  fontSize: "0.72rem",
                  color: t.ink50,
                  fontStyle: "italic",
                  marginBottom: "1rem",
                }}
              >
                White-label branding available on Pro and Agency plans.
              </p>
            )}

            <button
              onClick={handleGenerate}
              disabled={generating}
              style={{
                width: "100%",
                padding: "0.65rem",
                borderRadius: 8,
                border: "none",
                background: t.accent,
                color: "white",
                fontFamily: "var(--body)",
                fontSize: "0.88rem",
                fontWeight: 600,
                cursor: generating ? "not-allowed" : "pointer",
                opacity: generating ? 0.6 : 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: "0.5rem",
              }}
            >
              {generating ? (
                <Loader2 size={16} className="xsbl-spin" />
              ) : done ? (
                "Downloaded!"
              ) : (
                <>
                  <Download size={16} /> Generate &amp; download
                </>
              )}
            </button>
          </div>
        </div>
      )}

      <style>{`@keyframes xsbl-spin { to { transform: rotate(360deg); } } .xsbl-spin { animation: xsbl-spin 0.6s linear infinite; }`}</style>
    </>
  );
}
